// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/xavier.xiao/Downloads/perfect-design-master/node_modules/.pnpm/dumi@2.4.17_@babel+core@7.26.0_@swc+helpers@0.5.1_@types+node@20.5.1_@types+react@18.3.18_esl_xhg7povrd4igwe2llpmyml5ram/node_modules/dumi/theme-default/slots/HeaderExtra/index.js';
